### ISSUE TITLE
Support IE 11

### ISSUE THREAD

**Issue by GauthierPLM** [andrewvasilchuk/vue-lazy-youtube-video#10]
Currently, the builds provided with vue-lazy-youtube-video are not compatible with IE 11, and this may result in a complete breaking of the page using the component (rendering as only a white page).

Could you provide a build that supports IE 11?
Even if I hate to say this, about a 10th of my users browse my website with it, and our market being exclusively targetted at Korea (where IE is still used by many because of government regulations that imposed the use of some ActiveX plug-ins in the past but can't get ride of them as of today) and I can't reasonably ignore them.

The demo provided with the project illustrate the issue: just open it in IE 11 and you'll see that the page cannot render properly. A tool like browserlist and a proper configuration of Babel (or the use of core-js) might fix the issue.

**Comment by GauthierPLM** [comment]
I successfully made it work by adding `vue-lazy-youtube-video` to the `transpileDependencies` option in `vue.config.js`.

However, I notice that because the CSS uses variables, the CSS does not work correctly on IE.

**Comment by andrewvasilchuk** [comment]
@GauthierPLM, Thanks a lot. Build with support for IE11 will be shipped ASAP 😉.

**Comment by GauthierPLM** [comment]
Thank you very much.

If I may suggest a fix to the CSS, SASS or LESS could be used as a replacement, keeping users' ability to customise the style while avoiding the incompatibility with IE 11. The only other solution I found is [this ponyfill](https://jhildenbiddle.github.io/css-vars-ponyfill/#/).
