### ISSUE TITLE
Npm - Module parse failed: Unexpected token

### ISSUE THREAD

**Issue by songoo** [andrewvasilchuk/vue-lazy-youtube-video#12]
Hello, 

After clean install, when tiring to use `npm run watch`. Any advice welcomed :) .

```
ERROR in ./node_modules/vue-lazy-youtube-video/dist/vue-lazy-youtube-video.esm.js
Module parse failed: Unexpected token (130:33)
You may need an appropriate loader to handle this file type.
|                     ? h('iframe', {
|                         staticClass: 'y-video__media',
|                         attrs: { ...iframeAttributes, src: srcAttribute },
|                     })
|                     : [
 @ ./src/app.js 43:27-60
```

**Comment by songoo** [comment]
Hmm... Seems `babel@6` does not support spread `...` operator, 'spread' plugin for `@6` doesn't work also, and migration from `babel@6` to `babel@7` didn't go well for me, so I guess there is no help :) Since it's not directly this plugin issue, it's just lack of support of new syntax :( .

**Comment by songoo** [comment]
1.3 verson seems to work ok.

**Comment by andrewvasilchuk** [comment]
@songoo, Thanks for reporting. Seems like this issue is related to your bundler. Notice, that there is `dist/vue-lazy-youtube-video.min.js` file, which has no spread operator, so you can try to import this file directly.

**Comment by andrewvasilchuk** [comment]
@songoo, Can we close the issue?)
