### ISSUE TITLE
Feature request: events

### ISSUE THREAD

**Issue by caweidmann** [andrewvasilchuk/vue-lazy-youtube-video#16]
Hi there

Would it be possible to add events to the plugin that one can hook into? I'm thinking of two specifically that can be very useful:

1. `@thumbnailLoaded` (or something along those lines) which triggers after the thumbnail has fully loaded in the DOM.
2. `@ready` which triggers when the iframe has been injected into the DOM and has loaded. This would be useful for mobile when `autoplay` doesn't work so one can manually trigger the video to play after the "ready" event.

**Comment by enkota** [comment]
+1 would like to be able to trigger a Google Analytics event when the video is clicked on! @caweidmann has detailed the events pretty well!

**Comment by andrewvasilchuk** [comment]
@caweidmann, What about `<iframe />` load event: #20. What about thumbnail: you can listen to thumbnail events through `thumbnailListeners` prop.

**Comment by andrewvasilchuk** [comment]
@caweidmann, @enkota, Can we close the issue, or should we discuss more type of events developer might need to hook into?

**Comment by andrewvasilchuk** [comment]
@caweidmann, @enkota, Thanks for creating the issue 🙏 .

**Comment by caweidmann** [comment]
I haven't looked at `thumbnailListeners`, but if it's possible to catch a load event there then we can close this from my side.

**Comment by andrewvasilchuk** [comment]
@caweidmann, Yeah, this is possible. You can take a close look [here](https://github.com/andrewvasilchuk/vue-lazy-youtube-video/blob/dev/demo/App.vue).
