### ISSUE TITLE
Edge crash

### ISSUE THREAD

**Issue by drameryan** [andrewvasilchuk/vue-lazy-youtube-video#18]
When loaded with edge browser, the whole application crashes with the following error:
**SCRIPT1028: SCRIPT1028: Expected identifier, string or number**

Even the demo code on codesandbox is not loaded on edge.[https://codesandbox.io/s/x7nrwxq6qo](url)

**Comment by drameryan** [comment]
The problem happened with older versions of Edge. With the latest version it was resolved.

**Comment by goatandsheep** [comment]
It's still failing on IE

**Comment by andrewvasilchuk** [comment]
@goatandsheep, Thanks, I will investigate. By the way, what's the version of `vue-lazy-youtube-video` do you use?

**Comment by goatandsheep** [comment]
`2.3.0`

**Comment by goatandsheep** [comment]
To be specific this is the error:

```
Expected ')'
vuejs-app-bundle.js (163683,45)
```
![image](https://user-images.githubusercontent.com/5570628/98375895-c153eb00-2010-11eb-8cb0-31d36a69a633.png)

I suppose it might be from Vue.js configurations clashing? I'm not sure.

**Comment by goatandsheep** [comment]
@andrewvasilchuk this is duplicated by my coworker in #32
