### ISSUE TITLE
NPM: Module parse failed: Unexpected token

### ISSUE THREAD

**Issue by NtchPlayer** [andrewvasilchuk/vue-lazy-youtube-video#19]
Hi,
I just install vue lazy youtube video, but I have the same issue that @songoo, I read the conversation but I don't understand how I can import file 'dist/vue-lazy-youtube-video.min.js' directly.
In which file ? And where in this file ? (Or I can use a build of the plugin where this issus is solve ?) Thx you a lot for any answer :)

**Comment by songoo** [comment]
Heh, hello there :-)

I used (and still are happily using :) ) older version , so in "package.json"

```
  "dependencies": {
    "vue-lazy-youtube-video": "v1.3.0-beta.1",
```

This is latest version which worked for me, and so far its all good.

**Comment by NtchPlayer** [comment]
I change too for the v1.3.0-beta.1 and yeah that work for me ! Thx you a lot for your quick response ! I close the subject 👍
