### ISSUE TITLE
Access native YTPlayer events.

### ISSUE THREAD

**Issue by ajarti** [andrewvasilchuk/vue-lazy-youtube-video#20]
Thanks for a great plugin!

I was wondering how one could access the native iframe `YT.Player` events, namely `"onStateChange".`  I am looking to track stats on play time and buffering frequency.

Even if the plugin returned a reference to the player instance?

**Comment by ajarti** [comment]
Hi guys .. any help would be appreciated :)

**Comment by andrewvasilchuk** [comment]
@ajarti, Hello. Thanks for the issue. I'll handle during this week, and  will release a new version.

**Comment by ajarti** [comment]
That's brilliant @andrewvasilchuk many thanks in advance!

**Comment by andrewvasilchuk** [comment]
@ajarti, Again, thanks for creating the issue.

Here is how you can create `YT.Player` instance.

🚨 Don't forget to pass [enablejsapi](https://developers.google.com/youtube/player_parameters#enablejsapi) URL parameter

```html
<LazyYoutubeVideo
  src="https://www.youtube.com/embed/4JS70KB9GS0?enablejsapi=1"
  iframe-attributes="iframeAttributes"
  @load:iframe="onIframeLoad"
/>
```

```js
export default Vue.extend({
  // ...
  data() {
      iframeAttributes: {
        id: 'video',
      },
    }
  },
  methods: {
    onIframeLoad({ iframe }) {
      const id = iframe ? iframe.id : this.iframeAttributes.id
      const instance = new YT.Player(id, {  })
    },
  },
})
```

P.S Tip fo TS users: there is `LoadIframeEventPayload` type.

**Comment by andrewvasilchuk** [comment]
Full example [here](https://github.com/andrewvasilchuk/vue-lazy-youtube-video/blob/dev/demo/App.vue).

**Comment by ajarti** [comment]
@andrewvasilchuk You da bomb man .. thanks again.
