### ISSUE TITLE
Getting this error in Safari, but other browsers work fine.

### ISSUE THREAD

**Issue by delta0800** [andrewvasilchuk/vue-lazy-youtube-video#6]
<img width="1280" alt="Screenshot 2019-12-06 at 11 31 30 PM" src="https://user-images.githubusercontent.com/53184778/70338992-86858800-1880-11ea-82b7-bf9f0b1ca5e3.png">
<img width="1274" alt="Screenshot 2019-12-06 at 11 31 46 PM" src="https://user-images.githubusercontent.com/53184778/70338993-86858800-1880-11ea-8177-6322ac68bb11.png">

**Comment by andrewvasilchuk** [comment]
@delta0800, Thanks. I have researched a little but haven't find out a proper solution 😢.  But your issue gave me the idea of creating a prop named `iframeAttributes`, which will apply the value of that prop to the `<iframe />` element, so we can set any `<iframe />` attribute we want.

**Comment by andrewvasilchuk** [comment]
Added ability so set custom `<iframe />` attributes: 1ee83c4492740c83f4b895cf3f5cfbaf62b6c515. I am going to release a new minor version ASAP.

**Comment by delta0800** [comment]
Hi Andrew, 

How are you? Thanks for the quick response and effort. I will give a try later to resolve the iframe issue. 

Have a nice day.

Thanks 
Lawrence

**Comment by andrewvasilchuk** [comment]
@delta0800, I have noticed that YouTube gives you an `<iframe />` element which have attribute `allow`, set to `accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture`. I have also updated the value of the `allow` attribute to match the YouTube version. See 9c2e4ceaad4742819bbb79d834db679be935bcef.

**Comment by delta0800** [comment]
Hello Andrew, 

I saw that the new update with the allow attribute same as YouTube. Last night I tried to run npm update for the package somehow it still the old version contents. But I checked in package.json Have updated to 1.2.2 
Any advise? Please correct me if any silly mistakes I have made. Hope I can learn more from you. 

Thanks 
Lawrence

**Comment by andrewvasilchuk** [comment]
@delta0800, I have released a beta version. It's being tested right now, becaise as for now I am not sure it's stable. You can install a beta version running this command:
```bash
npm i vue-lazy-youtube-video@1.3.0-beta.0
```
I will publish a stable `1.3.0` realese as soon as I am sure everything works properly.

**Comment by andrewvasilchuk** [comment]
@delta0800, Actually there is no need for it. New version `1.3.0-beta.1` with SSR support is released.

**Comment by delta0800** [comment]
Hello Andrew, 

Thanks for the email. Noted that. 
Have the issue resolve at your end?  I will try tonight version 1.3.0 . The error message at safari actually is about the Allow attributes in iframe in my understanding. For the new release have you resolved it at your end? 

Thanks 
Lawrence

**Comment by delta0800** [comment]
Hello Andrew, 

How are you today? I have updated the package to the latest release. 
I still got the message without correct 'allow' attribute. Maybe i have made some mistake. 
Below are screenshot of my template. 


View blade

**Comment by andrewvasilchuk** [comment]
@delta0800, Sorry but still I do not know hove to solve this issue? Are you running your code on site with `HTTPS` protocol?

**Comment by delta0800** [comment]
Hello Andrew,

How are you? Today is Sat hope you have a great weekends. 

Sorry for the late reply this few days. I done some research also from others they have this problem also On Safari. 

I tried also to run it through https have the same problem too. Just to make sure with you there’s no issue with the code I write right? I will keep on trying if I have find the answer I will email you too. 

Wish you have a nice day. 

Thanks 
Lawrence

**Comment by andrewvasilchuk** [comment]
@delta0800, Thanks a lot!

**Comment by delta0800** [comment]
Happy New Year to you @Andrew.
Welcome 2020! 
Cheers !

**Comment by andrewvasilchuk** [comment]
@delta0800, Do not getting this issue anymore.

**Comment by delta0800** [comment]
Hello Sir, 

How are you? Hope you are fine. 
I am glad to hear that it’s fixed. I will check it. 

Thanks 
Lawrence
